apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master 
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis-master
        image: docker.io/fluxcapacitor/keyvalue-redis
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6379
        - containerPort: 7379 
