apiVersion: v1
kind: ReplicationController
metadata:
  name: loadtest 
  labels:
    app: loadtest 
spec:
  replicas: 1
  selector:
    name: loadtest 
  template:
    metadata:
      labels:
        name: loadtest 
    spec:
      containers:
      - name: loadtest 
        image: docker.io/fluxcapacitor/loadtest
        imagePullPolicy: "Always"
        env:
        - name: TEST_PATHNAME
          value: /root/tests/RecommendationServiceStressTest.jmx 
