apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra 
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    name: cassandra
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
      - name: cassandra
        image: docker.io/fluxcapacitor/cassandra
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7199
        - containerPort: 9042
        - containerPort: 9160
        - containerPort: 7000      
