apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: docker.io/fluxcapacitor/zookeeper
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 2181
