apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 8080 
  selector:
    name: airflow 
