apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-cache
  labels:
    app: prediction-cache
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-cache
  template:
    metadata:
      labels:
        name: prediction-cache
        hystrix.enabled: "true"
    spec:
      containers:
      - name: prediction-cache
        image: docker.io/fluxcapacitor/prediction-cache
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
#        livenessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 300 
#        readinessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 30 
