apiVersion: v1
kind: Service
metadata:
  name: kafka-0-8
spec:
  type: LoadBalancer
  ports:
  - name: native-kafka
    port: 9092
    targetPort: 9092
  - name: schema-registry
    port: 8081
    targetPort: 8081
  - name: rest-proxy
    port: 8082
    targetPort: 8082
  selector:
    name: kafka-0-8
