apiVersion: v1
kind: Service
metadata:
  name: airpal 
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 80 
    targetPort: 4123
  - name: admin
    port: 81
    targetPort: 4124
  selector:
    name: airpal 
