apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-worker 
  labels:
    app: presto-worker
spec:
  replicas: 1
  selector:
    name: presto-worker
  template:
    metadata:
      labels:
        name: presto-worker
    spec:
      containers:
      - name: presto-worker
        image: docker.io/fluxcapacitor/presto-worker-0.145
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7060 
