apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-master 
  labels:
    app: presto-master
spec:
  replicas: 1
  selector:
    name: presto-master
  template:
    metadata:
      labels:
        name: presto-master
    spec:
      containers:
      - name: presto-master
        image: docker.io/fluxcapacitor/presto-master-0.145
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7060 
