apiVersion: v1
kind: ReplicationController
metadata:
  name: clustered-tensorflow-worker0 
  labels:
    app: clustered-tensorflow-worker0
spec:
  replicas: 1
  selector:
    name: clustered-tensorflow-worker0
  template:
    metadata:
      labels:
        name: clustered-tensorflow-worker0
    spec:
      containers:
      - name: clustered-tensorflow-worker0
        image: docker.io/fluxcapacitor/clustered-tensorflow
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: PS_HOSTS
          value: ps0:2222,ps1:2222
        - name: WORKER_HOSTS
          value: worker0:2222,worker1:2222
        - name: JOB_NAME
          value: worker
        - name: TASK_INDEX
          value: "0"
        ports:
        - containerPort: 2222
