apiVersion: v1
kind: Service
metadata:
  name: clustered-tensorflow-master
  labels:
    job_name: master 
spec:
  type: LoadBalancer
  ports:
  - name: native-tensorflow 
    port: 2222
    targetPort: 2222
  selector:
    name: clustered-tensorflow-master
