apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-4-5-0
  labels:
    app: kibana-4-5-0
spec:
  replicas: 1
  selector:
    name: kibana-4-5-0
  template:
    metadata:
      labels:
        name: kibana-4-5-0
    spec:
      containers:
      - name: kibana-4-5-0
        image: docker.io/fluxcapacitor/kibana-4.5.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5601 
