apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-master
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: http
    port: 80 
    targetPort: 8754
  selector:
    name: jupyterhub-master
