apiVersion: v1
kind: Service
metadata:
  name: web-home 
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: web-home 
