apiVersion: v1
kind: Service
metadata:
  name: zeppelin-master
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: "http"
    port: 80 
    targetPort: 3123 
  - name: "websocket"
    port: 81 
    targetPort: 3124
  selector:
    name: zeppelin-master
